### ISSUE TITLE
Additional test for D<

### ISSUE THREAD

**Issue by ellerh** [gerryjackson/forth2012-test-suite#21]
I'd like to suggest the following test for `D<`:
```T{  0 1 1 0 D< -> FALSE }T```

While reading [lbForth's code](https://github.com/larsbrinkhoff/lbForth/blob/master/src/double.fth), I found this definition:
```: d<    rot > if 2drop -1 else u< then ;```
which looked suprisingly concise to me, but it doesn't handle the test correctly.  At the moment no other tests seems to expose the bug in lbForth's D<.

**Comment by gerryjackson** [comment]
Excellent suggestion, I'll incorporate it into the double number tests later today. I think that anything like this, where an implementation is incorrect but not detected by the test programs, should have a test included to detect the fault (if detectable of course).
Many thanks.

**Comment by gerryjackson** [comment]
Test added with similar test for negative operands. Also added for DU<
