### ISSUE TITLE
BUFFER: test fails on 64-bit system

### ISSUE THREAD

**Issue by leonwagner** [gerryjackson/forth2012-test-suite#32]
This line causes the subsequent test to fail on a 64-bit system:
`T{ 8 BUFFER: BUF:TEST -> }T`

It should probably be this for portability:
`T{ 2 CELLS BUFFER: BUF:TEST -> }T`

**Comment by gerryjackson** [comment]
Thanks for reporting this Leon. Fixed as recommended - sorry about the bug

**Comment by gerryjackson** [comment]
Issue closed
