### ISSUE TITLE
Incorrect way to skip test in fpzero-test.4th

### ISSUE THREAD

**Issue by leonwagner** [gerryjackson/forth2012-test-suite#36]
The test for floating-point signed zero support uses this to skip to the end of the file, leaving the [IF] unresolved:

```
-0E 0E 0E F~ [IF]
   cr cr .( ** System does not support floating point signed zero. **)
   cr    .( ** Therefore these tests have been skipped **) cr
   : goto-eof begin refill 0= until ;  goto-eof
[THEN]

```
That `[THEN]` should be moved to the end of the file and replaced by `[ELSE]`.

**Comment by gerryjackson** [comment]
Suggested solution used and definition GOTO-EOF deleted. Issue closed
