### ISSUE TITLE
Faults in blocktest tests when exercised against a 1 buffer cache

### ISSUE THREAD

**Issue by steverpalmer** [gerryjackson/forth2012-test-suite#7]
After release of V0.13, Peter Falth reported on comp.lang.forth problems with running the tests on a forth system with 1 buffer cache.  In particular:

    In TL7 (line 474) you test if there is only one buffer. if that is the case 
    you drop the parameters and push zeros and then exists. There is one drop 
    to much.

I've also reproduced this fault.

**Comment by steverpalmer** [comment]
Peter Falth found another bug that is evidence on forth systems with a 1 buffer cache:

    In TCSIRIR4 at line 653 you shift to the next block to start writing to it 
    but the old buffer is not updated so it will be overwritten and not committed 
    to the disk. Inserting an UPDATE SAVE-BUFFERS solved this. 

I've reproduced this fault also.

**Comment by steverpalmer** [comment]
With my forth configured for a single buffer block cache, I produced the following output running the tests against the fix/iss7 branch:

    IA32 Forth V0.3
    *********SCR # 23 
     0 Should show a (mostly) blank screen                             
     1                                                                 
     2                                                                 
     3                                                                 
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                                 
    SCR # 20 
     0 List of the First test block                                    
     1                                                                 
     2                                                                 
     3                                                                 
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                                 
    SCR # 29 
     0 List of the Last test block                                     
     1                                                                 
     2                                                                 
     3                                                                 
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                                 
    SCR # 24 
     0                                                                 
     1                                                                 
     2                                                                 
     3                                                                 
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                    End of Screen
    SCR # 27 
     0 Should show another (mostly) blank screen                       
     1                                                                 
     2                                                                 
     3                                                                 
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                                 
    ***Calculated Characters per Line: 64 
    *
    End of Block word tests

I get identical output when I reconfigure my forth system with a 4 buffer block cache.

**Comment by steverpalmer** [comment]
When running fix/iss7 against gforth 0.7 I get:

    Running ANS Forth and Forth 2012 test programs, version 0.13
    redefined ?DEFTEST1  *********Screen 27 not modified     
     0 Should show a (mostly) blank screen                             
     1                                                                 
     2                                                                 
     3                                                                 
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                                 
    Screen 20 not modified     
     0 List of the First test block                                    
     1                                                                 
     2                                                                 
     3                                                                 
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                                 
    Screen 29 not modified     
     0 List of the Last test block                                     
     1                                                                 
     2                                                                 
     3                                                                 
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                                 
    Screen 28 not modified     
     0                                                                 
     1                                                                 
     2                                                                 
     3                                                                 
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                    End of Screen
    Screen 25 not modified     
     0 Should show another (mostly) blank screen                       
     1                                                                 
     2                                                                 
     3                                                                  
     4                                                                 
     5                                                                 
     6                                                                 
     7                                                                 
     8                                                                 
     9                                                                 
    10                                                                 
    11                                                                 
    12                                                                 
    13                                                                 
    14                                                                 
    15                                                                 
    ***Given Characters per Line: 64 
    *
    End of Block word tests

    ---------------------------
            Error Report
    Word Set             Errors
    ---------------------------
    Core                    0
    Core extension          -
    Block                   0
    Double number           -
    Exception               -
    Facility                -
    File-access             -
    Locals                  -
    Memory-allocation       -
    Programming-tools       -
    Search-order            -
    String                  -
    ---------------------------
    Total                   0
    ---------------------------


    Forth tests completed

**Comment by gerryjackson** [comment]
Bug fixed by Steve Palmer and merged into the Master
